app:
   datasource:
      jdbc-url: jdbc:postgresql://localhost:5432/bank
      username: postgres
      password: password
      pool-size: 30
      driverClassName: org.postgresql.Driver


spring:
    jpa:
       properties:
          hibernate.jdbc.lob.non_contextual_creation: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop

